#!/bin/bash
#
# Just a little script to sanitize the package before releasing

echo "Cleaning package before releasing"
find . -name .cvsignore -exec rm {} \;
rm -rf ignore
rm -f cvsrelease
rm -f eb2_zipfile_crypt.py
echo "... done"
