#!/bin/bash
#
# Just a little script to sanitize the package before releasing

echo "Cleaning package before releasing"
find . -name .cvsignore -exec rm {} \;
rm -rf ignore
rm -f cvsrelease
rm -f win-inno.iss
rm -f win-setup.py
echo "... done"
